server:
  port: 8001

datasource-host: localhost
datasource-port: 33061
datasource-username: root
datasource-password: wc123456
datasource-db: my-crawler

spring:
  datasource:
    url: jdbc:mysql://${datasource-host}:${datasource-port}/${datasource-db}?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: ${datasource-username}
    password: ${datasource-password}

mybatis:
  codegen:
    enabled: true
    parent_pck: fit.wenchao.mycrawler
    author: wc
    db_url: jdbc:mysql://${datasource-host}:${datasource-port}/${datasource-db}?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    db_username: root
    db_password: wc123456
    controller_on: false
